

stages:
  - deploy


deploy_prod:
  stage: deploy
  script:
    - sudo cp -r * $TUTOR_DIR/edx-oauth2-llavemx
    - source $TUTOR_DIR/venv/bin/activate
    - cd $TUTOR_DIR
    - sudo pip install -e ./edx-oauth2-llavemx
    - sudo tutor images build openedx
    - sudo tutor local start -d
  tags:
    - edx
  only:
    refs:
      - main

